config/routes.rb
LionTamer::Application.routes.draw do
  match "/:server_name/:service/activate" => "machines#activate_service", :server_name => %r([^/;,?]+), :service => %r([^/;,?]+), :as => :activate_service
  match "/:server_name/:service/deactivate" => "machines#deactivate_service", :server_name => %r([^/;,?]+), :service => %r([^/;,?]+), :as => :deactivate_service
  match "/auth/:provider/callback" => "sessions#create", :as => :login
  match "/signout" => "sessions#destroy", :as => :logout
  match "/auth/failure" => "sessions#failure"

  resources :sessions

  resources :users

  root :to => 'machines#index'

end

app/models/machine.rb
class Machine 
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
      puts "#{name}=#{value}"
    end
  end

  def persisted?
    false
  end

  def get_server_name(server)
    name = %x[ssh #{server} hostname]
  end

  def get_full_info(server_name)
    server = LionAdmin::Base.new(server_name)
    name = server.hostname
    machine_serial = server.serialnumber
    services = server.services
    warranty = OSXwarranty::Base.new
    warranty_info = warranty.info(machine_serial)
    return {:name => name, :serial => machine_serial, :services => services, :warranty_info => warranty_info}
  end

  def activate(server_name, service)
    server = LionAdmin::Base.new(server_name)
    server.start_service(service)
  end

  def deactivate(server_name, service)
    server = LionAdmin::Base.new(server_name)
#    raise service.to_s
    server.stop_service(service)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
    ROLES = %w[admin viewer]

	def role_symbols
    	[role.to_sym]
  	end

  	def self.create_with_omniauth(auth)
	    create! do |user|
	      user.provider = auth["provider"]
	      user.uid = auth["uid"]
	      user.name = auth["info"]["name"]
	      user.role = 'viewer'
	    end
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def require_user
    unless current_user
      redirect_to "/auth/ldap"
      return false
    end
  end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
	before_filter :require_user
	def index
		@machines = Array.new
		@machines_fullinfo = Array.new
		APP_CONFIG['servers'].each do |server|
			mac = Machine.new
			fullinfo = mac.get_full_info(server)
			@machines_fullinfo.push(fullinfo)
		end
	end

	def activate_service
		server = Machine.new
		server.activate(params[:server_name],params[:service])
		respond_to do |format|
	  		format.html { redirect_to root_path, notice: "#{params[:service]} was activated" }
		end
	end

	def deactivate_service
		server = Machine.new
		server.deactivate(params[:server_name],params[:service])
		respond_to do |format|
	  		format.html { redirect_to root_path, notice: "#{params[:service]} was deactivated" }
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		auth = request.env["omniauth.auth"]
		user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
		session[:user_id] = user.id    
		respond_to do |format|
			format.html { redirect_to root_url, :notice => "Logged in!" }
		end
	end

	def destroy
		session[:user_id] = nil
		respond_to do |format|
			format.html { redirect_to root_url, :notice => "Logged out!" }
		end
	end

	def failure
		respond_to do |format|
			format.html { redirect_to root_url, :alert => "Incorrect login information" }
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def app_revision
		revision_file = File.join(Rails.root, "VERSION")
		if File.readable?(revision_file)
			IO.read(revision_file)
		else
			"unknown"
		end
	end
end

app/helpers/machines_helper.rb
module MachinesHelper
	def check_status(server,service)
		APP_CONFIG['servers'].each do |sr|
			if sr.match("#{server}")
				machine = LionAdmin::Base.new(sr)
				status = machine.check_if_running(service)
				return status
			end
		end
	end

	def fullstatus(server,service)
		APP_CONFIG['servers'].each do |sr|
			if sr.match("#{server}")
				machine = LionAdmin::Base.new(sr)
				fullstatus = machine.fullstatus(service)
				return fullstatus
			end
		end
	end

	def readlog(server,log)
		APP_CONFIG['servers'].each do |sr|
			if sr.match("#{server}")
				logfile = %x[ssh #{sr} tail -50 #{log}]
				return logfile
			end
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "LionTamer" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="<%= root_url %>">LionTamer</a>
        <div class="nav-collapse">
          <ul class="nav pull-right">
            <% if current_user %>
            <li class="divider-vertical"></li><li><%= link_to "Sign Out", logout_path %></li>
            <% else %>
            <li class="divider-vertical"></li>
            <li><%= link_to "Sign in", "/auth/ldap" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>


    <div class="container">
      <div class="content">
        <div class="row">
          <div class="span10 offset1">
            <%= yield %>
          </div>
        </div> <!-- /row -->
      </div><!--/content-->
      <div class="footer">
        <hr>
          <footer align="center">LionTamer v<%= app_revision %>, Powered by Ruby on Rails</footer>
      </div>
    </div> <!-- /container -->


    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/machines/_fullstatus.html.erb
<% fs = fullstatus(server_name,serv) %>
<dl class="dl-horizontal">
	<% fs.each do |key,val|%>
		<% unless val.blank? %>
			<% unless key.match("logPaths") %>
				<dt><%= key %>:</dt>
				<dd><%= val.to_s.downcase %></dd>
				<% else %>
					<% val.each do |k,v| %>
						<dt><%= k.to_s %>:</dt>
						<dd><%= link_to "Log", "##{server_name.split(/\./).first}_#{v.split(/\//).last.split(/\./).first}", "data-toggle" => "modal" %><div class="modal hide fade" id="<%= server_name.split(/\./).first + '_' + v.to_s.split(/\//).last.split(/\./).first %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"><%= render "logs", :server_name => server_name, :logfile => v.to_s %></div></dd>
					<% end %>
			<% end %>
		<% end %>
	<% end %>

</dl>

app/views/machines/_logs.html.erb
<% log = readlog(server_name,logfile) %>
<div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3 id="myModalLabel"><%= logfile %></h3>
  </div>
  <div class="modal-body">
    <pre><%= log.to_s %></pre>
  </div>

app/views/machines/index.html.erb
<% i = 1 %>
<div class="accordion" id="accordion1">
<% @machines_fullinfo.each do |machine| %>
	<% fullinfo = fullstatus(machine[:name],"info") %>

   		<div class="accordion-group">
	     	<div class="accordion-heading">
	    		<a class="accordion-toggle" data-toggle="collapse" data-parent="accordion1" href="#collapse<%= i %>"><%= machine[:name]%></a>
	    	</div>
			<div id="collapse<%= i %>" class="accordion-body collapse in">
				<div class="accordion-inner">
					<dl class="dl-horizontal">
						<dt>Name:</dt>
						<dd><%= fullinfo['computerName'] %></dd>

						<dt>Serial:</dt>
						<dd><%= machine[:serial]%></dd>

						<dt>Model:</dt>
						<dd><%= machine[:warranty_info][:model] %></dd>

						<dt>CPU:</dt>
						<dd><%= "#{number_with_precision(fullinfo['computerInfo']['cpuSpeed'].to_f/1000000000.to_f, :precision => 2)} GHz #{fullinfo['computerInfo']['cpuKind']}" %></dd>

						<dt>Memory:</dt>
						<dd><%= "#{number_with_precision(fullinfo['computerInfo']['memorySize'].to_f/1000000000.to_f, :precision => 2)} GB"%></dd>

						<dt>CPU Usage:</dt>
						<dd><%= "#{number_with_precision(fullinfo['cpuUsageBy100'].to_f/100.to_f, :precision => 2)}%"%></dd>

						<dt>IP Address:</dt>
						<dd><%= fullinfo['interfaceInfosArray'].first['ipAddress'] %></dd>

						<dt>Server Version:</dt>
						<dd><%= fullinfo['version']%></dd>

						<dt>Kernel Version:</dt>
						<dd><%= fullinfo['kernelVersion']%></dd>

						<dt>Uptime:</dt>
						<dd><%= Time.diff(Time.now, fullinfo['bootTime'])[:diff] %></dd>

						<dt>Repair Covered:</dt>
						<dd><%= machine[:warranty_info][:repair_covered] %> </dd>

						<dt>Expiration Date:</dt>
						<dd><%= machine[:warranty_info][:expiration_date] %></dd>

						<dt>ASD:</dt>
						<% if machine[:warranty_info][:asdinfo].nil? then machine[:warranty_info][:asdinfo] = "unknown" end %>
						<dd><%= machine[:warranty_info][:asdinfo].to_s %></dd>

						<dt>Boot Volume:</dt>
						<dd><%= fullinfo['bootVolume'] %></dd>

					</dl>


					<div class="accordion" id="accordion2">
						<% machine[:services].each do |serv| %>
						<% unless serv.match(/info|certs|config|accounts|bonjour|backup|filebrowser|network|proxy|signaler|teams/) %>
							<% status = check_status(machine[:name],serv) %>
								<div class="accordion-group">
									<div class="accordion-heading">
											<% if status == true %>
											<a class="accordion-toggle  badge-success" data-toggle="collapse" data-parent="accordion2" href="#collapse_<%= machine[:name].split(/\./).first + '_' + serv %>"><%= serv %></a>
											<% else %>
											<a class="accordion-toggle  badge-warning" data-toggle="collapse" data-parent="accordion2" href="#collapse_<%= machine[:name].split(/\./).first + '_' + serv %>"><%= serv %></a>
											<% end %>
									</div>
									<div id="collapse_<%= machine[:name].split(/\./).first + '_' + serv %>" class="accordion-body collapse in">
										<div class="accordion-inner">
											<% if status == true %>
											<%= link_to ' Deactivate', {:controller => "machines", :action => "deactivate_service", :server_name => machine[:name], :service => serv}, confirm: "Are you sure you want to deactivate #{serv}?", :class => "pull-right icon-remove btn btn-primary btn-mini" %>
												<%= render "fullstatus", :server_name => machine[:name], :serv => serv %>
											<% else %>
											<%= link_to ' Activate', {:controller => "machines", :action => "activate_service", :server_name => machine[:name], :service => serv}, confirm: "Are you sure you want to activate #{serv}?", :class => "pull-right icon-ok btn btn-primary btn-mini" %>
											<% end %>
										</div>
									</div>
								</div>
							<% end %>
						<% end %>
					</div>
					
				</div>
			</div>
	    </div>
    <% i = i + 1 %>
<% end %>
</div>